### ISSUE TITLE
Error: <twisted.python.failure.Failure builtins.OSError: Not a gzipped file (b'<!')>

### ISSUE THREAD

**Issue by Ian4869** [Gerapy/GerapyPlaywright#3]
@Germey  你好，当存在 middleware  'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 时
使用PlaywrightRequest 会报题目所示错误

**Comment by Germey** [comment]
你好，可以提供下如下信息吗：
* 系统和版本
* Python 和版本
* Gerapy Playwright 的版本
* 你的具体操作说明

**Comment by Ian4869** [comment]
macOS Mojave 10.14.6
python 3.7.10   scrapy 2.5.1
Gerapy Playwright 0.2.0
测试网址 http://www.jggw.suzhou.gov.cn/

`        for url in self.start_urls:
            meta_info = {
                "origin_url": url,
                "job_id": self.job_id,
                "source": "",
                "AJAX": self.ajax,
                "depth": 0,
                "internal": True,
                "source_tag": "",
                "proxy_strategy": self.proxy_strategy
            }

            yield PlaywrightRequest(url, callback=self.parse_page, errback=self.proc_error, meta=meta_info)`

**Comment by zhutuo** [comment]
我也发现有这个问题。是发生在_process_request返回response后。
先是这样的错误提示：
`Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
result = current_context.run(gen.send, result)`

然后才是
`
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
result = current_context.run(gen.send, result)
File "/usr/local/lib/python3.8/dist-packages/scrapy/core/downloader/middleware.py", line 54, in process_response
response = yield deferred_from_coro(method(request=request, response=response, spider=spider))
File "/usr/local/lib/python3.8/dist-packages/scrapy/downloadermiddlewares/httpcompression.py", line 62, in process_response
decoded_body = self._decode(response.body, encoding.lower())
File "/usr/local/lib/python3.8/dist-packages/scrapy/downloadermiddlewares/httpcompression.py", line 82, in _decode
body = gunzip(body)
File "/usr/local/lib/python3.8/dist-packages/scrapy/utils/gz.py", line 27, in gunzip
chunk = f.read1(8196)
File "/usr/lib/python3.8/gzip.py", line 305, in read1
return self._buffer.read1(size)
File "/usr/lib/python3.8/_compression.py", line 68, in readinto
data = self.read(len(byte_view))
File "/usr/lib/python3.8/gzip.py", line 479, in read
if not self._read_gzip_header():
File "/usr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'<!')`

**Comment by zhutuo** [comment]
经测试，同样的代码，在不跟scrapy联合使用时，程序完全正常

**Comment by zhutuo** [comment]
改成如下，可解决问题：
`                if not response:
                    logger.error(
                        'get null response by playwright of url %s', request.url)

                # Necessary to bypass the compression middleware (?)
                headers = response.headers
                headers.pop('content-encoding', None)
                headers.pop('Content-Encoding', None)

                response = HtmlResponse(
                    page.url,
                    status=response.status,
                    headers=headers,
                    body=content,
                    encoding='utf-8',
                    request=request
                )
                return response`

**Comment by Germey** [comment]
@zhutuo 感谢，我修复一下

**Comment by Germey** [comment]
Fixed in 0.2.3, please have a try.
